"""
  This is the second part of the pipeline. It takes the parsed AssetModel
  and generates detection rules for both Suricata and Zeek.
 
  The two engines work differently, so I handled them separately.
  For Suricata, I generate individual rules along with an IP allow-list
  that the rules can use.
 
  For Zeek, instead of generating lots of rules, I generate one generic
  detection script and populate it with the asset information. This way,
  the script stays the same and only the asset data changes for different
  testbeds.
 """

from __future__ import annotations
from asset_model import AssetModel

SID_BASE = 1000000  # Suricata rule IDs for this generator start here

# Suricata: enumerated signatures + a reusable IP variable group

def to_suricata(model: AssetModel) -> str:
    lines = []
    lines.append("# Auto-generated by scd-ids-rulegen")
    lines.append("# Source: SCD asset & GOOSE-flow baseline")
    lines.append("")
    lines.append("# Variable group: add this to suricata.yaml under vars.address-groups ---")
    known_ips = sorted(model.known_ips())
    lines.append(f"# AUTHORIZED_IEDS: \"[{','.join(known_ips)}]\"")
    lines.append("")

    sid = SID_BASE

    # Rule 1: Alert if an IP on the station network isn't part of the SCD asset inventory.
    lines.append("# Detect traffic from IPs that are not part of the SCD asset list.")
    lines.append(
        f'alert ip !$AUTHORIZED_IEDS any -> any any '
        f'(msg:"Unauthorized device on substation network (not in SCD asset list)"; '
        f'sid:{sid}; rev:1; classtype:policy-violation;)'
    )
    sid += 1
    lines.append("")

    # Rule 2: Check that GOOSE messages use the expected APPID for the
    # configured publisher. Flag anything that doesn't match.
    lines.append("# Rules: GOOSE frames using an APPID not assigned to any known publisher")
    known_appids = sorted({f.appid for f in model.goose_flows if f.appid})
    for flow in model.goose_flows:
        publisher = model.get_asset(flow.publisher_asset_id)
        if publisher is None or not publisher.ip:
            continue
        lines.append(
            f'alert ip !{publisher.ip} any -> any any '
            f'(msg:"GOOSE traffic (APPID {flow.appid}) from unexpected source, '
            f'expected publisher {publisher.ied_name}"; '
            f'sid:{sid}; rev:1; classtype:policy-violation;)'
        )
        sid += 1

    lines.append("")
    return "\n".join(lines)

# Zeek: one generic script + a populated data table

_ZEEK_SCRIPT_TEMPLATE = """\

# Auto-generated from the parsed SCD file.
# The detection logic stays the same for every testbed.
# Only the asset and GOOSE publisher data is regenerated when the
# SCD changes.

module SCDBaseline;

export {{
    redef enum Notice::Type += {{
        Unauthorized_Device,
        Unexpected_GOOSE_Publisher,
    }};
}}

# --- Data: populated from the SCD asset model ---
global known_ips: set[addr] = {{
{ip_entries}
}};

# publisher IP -> expected APPID, keyed as a string for simplicity
global known_goose_publishers: table[addr] of string = {{
{goose_entries}
}};

# Detection logic: generic, does not need to change per testbed

event connection_established(c: connection)
    {{
    if ( c$id$orig_h !in known_ips )
        {{
        NOTICE([$note=Unauthorized_Device,
                $msg=fmt("Connection from IP not in SCD asset baseline: %s", c$id$orig_h),
                $conn=c]);
        }}
    }}

# TODO:
# Add GOOSE-specific event handling once the Zeek event exposed by the
# Malcolm ICS analyzer is confirmed.
#
# The asset model already contains the expected publisher -> APPID
# mapping, so this data can be used to detect unexpected APPIDs.
"""


def to_zeek(model: AssetModel) -> str:
    ip_entries = ",\n".join(f"    {ip}" for ip in sorted(model.known_ips()))

    goose_lines = []
    for flow in model.goose_flows:
        publisher = model.get_asset(flow.publisher_asset_id)
        if publisher is None or not publisher.ip or not flow.appid:
            continue
        goose_lines.append(f'    [{publisher.ip}] = "{flow.appid}"')
    goose_entries = ",\n".join(goose_lines)

    return _ZEEK_SCRIPT_TEMPLATE.format(ip_entries=ip_entries, goose_entries=goose_entries)


if __name__ == "__main__":
    import sys
    sys.path.insert(0, ".")
    from parser import parse_scd

    scd_path = sys.argv[1] if len(sys.argv) > 1 else "../sample_data/example.scd"
    model = parse_scd(scd_path)

    print("=" * 70)
    print("SURICATA")
    print("=" * 70)
    print(to_suricata(model))

    print("=" * 70)
    print("ZEEK")
    print("=" * 70)
    print(to_zeek(model))
